language: go

go: 1.12.x

before_install:
  - go get github.com/magefile/mage
  - mage vendor

script:
  - mage check
  - mage testcover

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

jobs:
  include:
  - stage: test
  - stage: deploy
    os: linux
    if: tag IS present
    name: "Github Releases"
    script: skip
    before_deploy: "chmod +x scripts/dist.sh && scripts/dist.sh"
    deploy:
    - provider: releases
      api_key: $GITHUB_API_KEY
      skip_cleanup: true
      draft: true
      file_glob: true
      file:
      - dist/*.zip
      on:
        branch: release
        tags: true

branches:
  except:
  - gh-pages


