build: off

clone_folder: c:\gopath\src\github.com\kasvith\kache

environment:
  GOPATH: c:\gopath

stack: go 1.12

before_test:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/magefile/mage
  - mage vendor
  - mage check

test_script:
  - mage test

cache:
  - '%LocalAppData%\go-build'
  - '%GOPATH%\pkg\mod'
